
title = "OKC Robotics Beta 2022 Parameters"
competition = false

[ui]
gamepad1_id = 0
gamepad2_id = 2

[robot]
neo_550_ticks_per_rev = 42
neo_ticks_per_rev = 42
falcon_ticks_per_rev = 2048

[swerve]
# assumes our modules are located in a square, everything should be the same distance from the center
# units are in meters
x_disp = 0.216
y_disp = 0.216

[swerve.drive_pid]
kP = 0.0
kI = 0.1
# kI = 0.0
kD = 0.0

[swerve.steer_pid]
# kP = 0.00005
kP = 0.004
kI = 0.0
kD = 0.0

[swerve.heading_pid]
kP = 0.0
kI = 0.0
kD = 0.0

[swerve.offset]
left_front_offset = 209.0
left_back_offset = 72.5
right_front_offset = 236.1
right_back_offset = 11.3