title = "OKC Robotics 2023 Parameters"
competition = false

[ui]
gamepad1_id = 0
gamepad2_id = 1

[robot]
neo_550_ticks_per_rev = 42
neo_ticks_per_rev = 42
falcon_ticks_per_rev = 2048
work = true

[swerve]
# assumes our modules are located in a square, everything should be the same distance from the center
# units are in meters
x_disp = 0.216
y_disp = 0.216
# stuff for swerve modules and odometry and stuff
l2_gear_ratio = 6.75
wheel_diameter = 4.0
inches_to_meters = 0.0254 # yo unexpected 254!
drive_max_output = 1
drive_open_loop = 1
steer_max_output = 1
steer_open_loop = 0.0

[swerve.dist_pid]
kP = 0.5
kI = 0.0
kD = 0.0

[swerve.drive_pid]
kP = 0.5
kI = 0.0
# kI = 0.0
kD = 0.0

[swerve.steer_pid]
kP = 0.004
kI = 0.0
kD = 0.0

[swerve.heading_pid]
kP = 0.04
kI = 0.0
kD = 0.0

[swerve.offset]
left_front_offset = 210.0
left_back_offset = 79.0
right_front_offset = 10.0
right_back_offset = 153.0

[arm]
offset = -330
lift_limit = 110
extend_limit = 95
max_output = 0.6
arm_open_loop = 1
extend_open_loop = 0.5

# right in front of the robot to pick stuff up
[arm.pickup]
extend_setpoint = 79.5
arm_setpoint = 32

[arm.score_high]
extend_setpoint = 90.5
arm_setpoint = 94

[arm.score_medium]
extend_setpoint = 61.5
arm_setpoint = 72

[arm.negative_pickup]
extend_setpoint = 79.5
arm_setpoint = -33

[arm.negative_score_high]
extend_setpoint = 90.5
arm_setpoint = -94

[arm.negative_score_medium]
extend_setpoint = 61.5
arm_setpoint = -72


[arm.lift_pid]
kP = 0.05
kI = 0
kD = 0

[arm.extend_pid]
kP = 0.06
kI = 0
kD = 0.0

[claw]
open = 0
cube = 1
cone = 5

[claw.claw_pid]
kP = 0.01
kI = 0
kD = 0
