title = "OKC Robotics 2023 Parameters"
competition = false

[ui]
gamepad1_id = 0
gamepad2_id = 1

[robot]
neo_550_ticks_per_rev = 42
neo_ticks_per_rev = 42
falcon_ticks_per_rev = 2048
work = true

[swerve]
# assumes our modules are located in a square, everything should be the same distance from the center
# units are in meters
x_disp = 0.216
y_disp = 0.416
# stuff for swerve modules and odometry and stuff
l2_gear_ratio = 6.75
wheel_diameter = 4.0
inches_to_meters = 0.0254 # yo unexpected 254!
drive_max_output = 1
drive_open_loop = 1
steer_max_output = 1
steer_open_loop = 0.0
slew_limit = 2
turn_deadband_ = 0.3
strafe_deadband_ = 0.15
drive_deadband_ = 0.1
invert_threshold_ = 100.0
center_deadband_ = 0.05
speed_mod = 0.8
swerve_open_loop = 0.5
braking_speed_mod = 0.5
braking_open_loop = 1
fast_speed_mod = 1.5
fast_swerve_open_loop = 0.1

[swerve.dist_pid]
kP = 0.5
kI = 0.0
kD = 0.0

[swerve.drive_pid]
kP = 0.5
kI = 0.0
# kI = 0.0
kD = 0.0

[swerve.steer_pid]
kP = 0.005
kI = 0.0
kD = 0.000005
degrees = 180
tolerance = 2

[swerve.heading_pid]
kP = 0.04
kI = 0.0
kD = 0.0

[swerve.offset]
left_front_offset = 210.0
left_back_offset = 79.0

right_front_offset = 10.0
right_back_offset = 153.0

[auto_balance]
run_up_speed = 0.4
tilted_speed = 0.2
tilted_threshold = 15.0
reverse_threshold = 9.0
pitch_threshold = 1.0
drive_backward_speed = -0.2
timeout = 1.4

[arm]
offset = -327
lift_limit = 110
extend_limit = 95
max_output = 0.7
arm_open_loop = 10
extend_open_loop = 10
arm_pos_tolerance =  2.5
arm_vel_tolerance =  3.0
extend = 0.5
position_increment
extend_power = 69

# right in front of the robot to pick stuff up
[arm.pickup]
extend_setpoint = 30.0
arm_setpoint = 43.0
intake_setpoint = -45.0

[arm.score_high]
extend_setpoint = 65.0
arm_setpoint = 105.0
intake_setpoint = -40.0

[arm.score_medium]
extend_setpoint = 20.0
arm_setpoint = 94.0
intake_setpoint = -40.0

[arm.negative_pickup]
extend_setpoint = 30.0
arm_setpoint = -42.0
intake_setpoint = 20.0

[arm.negative_score_high]
extend_setpoint = 65.0
arm_setpoint = -105.0
intake_setpoint = 40.0

[arm.negative_score_medium]
extend_setpoint = 20.0
arm_setpoint = -90.0
intake_setpoint = 52.0

[arm.negative_human_player]
extend_setpoint = 5.0
arm_setpoint = -40.0
intake_setpoint = -87.0

[arm.human_player]
extend_setpoint = 5.0
arm_setpoint = 40.0
intake_setpoint = 87.0

[arm.lift_pid]
kP = 0.05
kI = 0
kD = 0
kF = 0.001

[arm.extend_pid]
kP = 0.06
kI = 0
kD = 0.0

[claw]
open = 0
cube = 1
cone = 5

[claw.claw_pid]
kP = 0.01
kI = 0
kD = 0

[intake]
tilt_offset = -55.0
intake_power = 0.7
idle_power = -0.03

[intake.wrist_pid]
kP = 0.005
kI = 0.0
kD = 0.0

[camera]
res = 240