name: CI
run-name: ${{ github.event.pull_request.head.ref }}
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
jobs:
   # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        context: $GITHUB_WORKSPACE

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # Grant write permission for gradlew
    - name: Grant write permission for gradlew
      run: chmod +rw gradlew

    # Install a roboRIO toolchain
    - name: Install RoboRIO Toolchain
      run: ./gradlew installRoboRioToolchain

    # Copy the deploy directory explicitly
    - name: Copy Deploy Configuration
      run: ./gradlew copyDeployDir

    - name: Show Files
      if: always()
      run: |
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/debug/
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/debug/src/main/deploy
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/release/
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/release/src/main/deploy

    - name: Show Files 2
      if: always()
      run: |
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/debug/
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/debug/src/main/deploy
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/release/
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/release/src/main/deploy

    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      if: always()
      run: ./gradlew build --build-cache

    - name: Show Files Again
      if: always()
      run: |
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/debug/
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/debug/src/main/deploy
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/release/
        ls -a $GITHUB_WORKSPACE/build/test-results/frcUserProgramTest/linuxx86-64/release/src/main/deploy

    - name: Show Files Again 2
      if: always()
      run: |
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/debug/
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/debug/src/main/deploy
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/release/
        ls -a ${{ github.workspace }}/build/test-results/frcUserProgramTest/linuxx86-64/release/src/main/deploy

    # Upload test artifacts
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        path: ${{ github.workspace }}/build/test-results/frcUserProgramTest